services:
  - type: web
    name: alumbrado-publico-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: alumbrado-publico-2024-seguro-cambiar-esto
      - key: ADMIN_EMAIL
        value: cristian.rauz@technovahosting.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: DATABASE_URL
        value: sqlite:./reports.db
